// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReportsSystemAPI.Infra;

namespace ReportsSystemAPI.Migrations
{
    [DbContext(typeof(RSApiContext))]
    [Migration("20190901070427_RSMigration")]
    partial class RSMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ReportsSystemApi.Domain.Entities.Atividade", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dataAtividade");

                    b.Property<DateTime>("dataCadastro");

                    b.Property<string>("descricao");

                    b.HasKey("id");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("ReportsSystemApi.Domain.Entities.AtividadeUsuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Usuarioid");

                    b.Property<int?>("atividadeid");

                    b.HasKey("id");

                    b.HasIndex("Usuarioid");

                    b.HasIndex("atividadeid");

                    b.ToTable("AtividadeUsuarios");
                });

            modelBuilder.Entity("ReportsSystemApi.Domain.Entities.Perfil", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("descricao");

                    b.HasKey("id");

                    b.ToTable("Perfis");
                });

            modelBuilder.Entity("ReportsSystemApi.Domain.Entities.Relatorio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("atividadeid");

                    b.Property<DateTime>("dataFim");

                    b.Property<DateTime>("dataInicio");

                    b.Property<string>("descricao");

                    b.Property<int?>("usuarioid");

                    b.HasKey("id");

                    b.HasIndex("atividadeid");

                    b.HasIndex("usuarioid");

                    b.ToTable("Relatorios");
                });

            modelBuilder.Entity("ReportsSystemApi.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("login");

                    b.Property<string>("nome");

                    b.Property<string>("senha");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ReportsSystemApi.Domain.Entities.UsuarioPerfil", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("perfilid");

                    b.Property<int?>("usuarioid");

                    b.HasKey("id");

                    b.HasIndex("perfilid");

                    b.HasIndex("usuarioid");

                    b.ToTable("UsuarioPerfils");
                });

            modelBuilder.Entity("ReportsSystemApi.Domain.Entities.Vinculo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IES");

                    b.Property<int>("orgao");

                    b.Property<int?>("usuarioid");

                    b.HasKey("id");

                    b.HasIndex("usuarioid");

                    b.ToTable("Vinculos");
                });

            modelBuilder.Entity("ReportsSystemApi.Domain.Entities.AtividadeUsuario", b =>
                {
                    b.HasOne("ReportsSystemApi.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuarioid");

                    b.HasOne("ReportsSystemApi.Domain.Entities.Atividade", "atividade")
                        .WithMany()
                        .HasForeignKey("atividadeid");
                });

            modelBuilder.Entity("ReportsSystemApi.Domain.Entities.Relatorio", b =>
                {
                    b.HasOne("ReportsSystemApi.Domain.Entities.Atividade", "atividade")
                        .WithMany()
                        .HasForeignKey("atividadeid");

                    b.HasOne("ReportsSystemApi.Domain.Entities.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid");
                });

            modelBuilder.Entity("ReportsSystemApi.Domain.Entities.UsuarioPerfil", b =>
                {
                    b.HasOne("ReportsSystemApi.Domain.Entities.Perfil", "perfil")
                        .WithMany()
                        .HasForeignKey("perfilid");

                    b.HasOne("ReportsSystemApi.Domain.Entities.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid");
                });

            modelBuilder.Entity("ReportsSystemApi.Domain.Entities.Vinculo", b =>
                {
                    b.HasOne("ReportsSystemApi.Domain.Entities.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid");
                });
#pragma warning restore 612, 618
        }
    }
}
