-- MySQL Script generated by MySQL Workbench
-- Tue Aug 27 12:38:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`vinculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vinculo` (
  `id_vinculo` INT NOT NULL,
  `ies` VARCHAR(5) NOT NULL,
  `orgao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_vinculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  `vinculo_id` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_vinculo1_idx` (`vinculo_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_vinculo1`
    FOREIGN KEY (`vinculo_id`)
    REFERENCES `mydb`.`vinculo` (`id_vinculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfil` (
  `id_perfil` INT NOT NULL,
  `descricao` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`relatorio` (
  `id_relatorio` INT NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id_relatorio`),
  INDEX `fk_relatorio_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_relatorio_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`atividade` (
  `id_atividade` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `data_atividade` DATE NOT NULL,
  `data_cadastro` DATE NOT NULL,
  `relatorio_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id_atividade`),
  INDEX `fk_atividade_relatorio1_idx` (`relatorio_id` ASC) VISIBLE,
  INDEX `fk_atividade_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_atividade_relatorio1`
    FOREIGN KEY (`relatorio_id`)
    REFERENCES `mydb`.`relatorio` (`id_relatorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividade_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_perfil` (
  `usuario_id` INT NOT NULL,
  `perfil_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `perfil_id`),
  INDEX `fk_usuario_has_perfil_perfil1_idx` (`perfil_id` ASC) VISIBLE,
  INDEX `fk_usuario_has_perfil_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_perfil_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_perfil_perfil1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `mydb`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
